### ISSUE TITLE
Two-factor authentication (TOTP)

### ISSUE THREAD

**Issue by nyuszika7h** [corellium/corellium-api#3]
When trying to log in to an account with two-factor authentication enabled, I get the following error:

```
/home/nyuszika7h/corellium/node_modules/corellium-api/src/util/fetch.js:42
        throw new CorelliumError(body, res.status);
              ^

CorelliumError: Invalid TOTP.
    at fetch (/home/nyuszika7h/corellium/node_modules/corellium-api/src/util/fetch.js:42:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /home/nyuszika7h/corellium/node_modules/corellium-api/src/corellium.js:76:25
    at async Corellium.getToken (/home/nyuszika7h/corellium/node_modules/corellium-api/src/corellium.js:88:17)
    at async Corellium.login (/home/nyuszika7h/corellium/node_modules/corellium-api/src/corellium.js:101:9)
    at async file:///home/nyuszika7h/corellium/screenshot.js:30:1 {
  field: undefined,
  code: 403
}
```

This appears to be undocumented. I have tried the `totp` field with a number and string value to no avail, it still throws the same error.

**Comment by strazzere** [comment]
Hi there -- thanks for filing the issue.

The correct field to utilize would be `totpToken` when requesting the login.

I'll attempt to get this added within the next few days to the documentation. Sorry for the confusion.

**Comment by strazzere** [comment]
This should be all set now, will republish docs shortly as well.
